BSA-18 | Logic for turd frequency
ohmlnz/bird-sh-t-avoider pull request #33
Opened 2021-09-28 23:50 UTC by danmcgill6

- Extracted turd logic

2021-09-29 04:01 UTC, ohmlnz requested changes

2021-09-29 04:01 UTC, ohmlnz commented on engine/src/systems/bird.js
> +  // If birds are on the screen
That comment is not totally correct. We're simply checking if there are any birds in the current scene. They can be hidden, especially at the beginning of a level. As a matter of fact, we only start to move them around on line 37 with `updateBirdPosition`

2021-09-29 04:01 UTC, ohmlnz commented on engine/src/systems/character.js
> +    Matter.Body.setVelocity(character.body, { x: 5.5 * character.acceleration, y: velocity.y });
🏃‍♂️💨

2021-10-02 14:04 UTC, danmcgill6 commented on engine/src/systems/helpers/bird.js
> +    newBird.turds = new Array(randomized(5, 1)).fill(turd);
Ahhhhhhhhhhhhhh nice catch, makes sense.

2021-10-02 14:10 UTC, danmcgill6 commented on engine/src/systems/bird.js
> +  // If birds are on the screen
@ohmlnz Agreed, I still cant push to the branch thoe to change it

2021-10-02 14:10 UTC, danmcgill6 commented on engine/src/systems/character.js
> +    Matter.Body.setVelocity(character.body, { x: 5.5 * character.acceleration, y: velocity.y });
hehehehhehehehe

2021-10-02 14:37 UTC, ohmlnz approved these changes

2021-10-02 15:00 UTC, merged