Bsa 6 main menu
ohmlnz/bird-sh-t-avoider pull request #43
Opened 2021-11-28 17:12 UTC by danmcgill6

**Story:** [STORY_TITLE](STORY_URL)

**Changes:**

- REPLACE_ME

2021-12-27 00:04 UTC, ohmlnz requested changes
Great job implementing both local storage and navigation into the game! I've left a bunch of comments, most of them being cosmetic stuff. 

Two things I wasn't able to leave comments for though:

1. `.DS_Store` should be removed, it's a metadata file specific to macos that contains info about the folder (icon size, background color, etc.). I've added it to our `.gitignore` in one of my previous stories, you should be able to see it if your branch has been rebased
2. I think by convention everything that gets compiled should be within `src`. I'm having a hard time following the new structure you implemented. We can talk about it in person on Tuesday.

2021-12-28 23:17 UTC, danmcgill6 commented on engine/src/game.js
> +              accessibilityLabel="Start avoiding shit"
I'm actually not sure what this label does, whats displayed is the title

2021-12-28 23:35 UTC, ohmlnz commented on engine/utils/localStorage.ts
> +    console.log("error", e);
[https://trello.com/c/ll2TK2PV/35-implement-proper-error-handling-to-logging-service](https://trello.com/c/ll2TK2PV/35-implement-proper-error-handling-to-logging-service)

2021-12-28 23:40 UTC, ohmlnz commented on engine/src/game.js
> +              accessibilityLabel="Start avoiding shit"
> Great job implementing both local storage and navigation into the game! I've left a bunch of comments, most of them being cosmetic stuff.
> 
> Two things I wasn't able to leave comments for though:
> 
> 1. `.DS_Store` should be removed, it's a metadata file specific to macos that contains info about the folder (icon size, background color, etc.). I've added it to our `.gitignore` in one of my previous stories, you should be able to see it if your branch has been rebased
> 2. I think by convention everything that gets compiled should be within `src`. I'm having a hard time following the new structure you implemented. We can talk about it in person on Tuesday.

[https://trello.com/c/sGOiRWZz/36-explore-refactoring-file-structure](https://trello.com/c/sGOiRWZz/36-explore-refactoring-file-structure)

2021-12-29 00:00 UTC, ohmlnz commented on engine/screens/MainMenu/styles.ts
> +    backgroundColor: "#fff",
[https://trello.com/c/Ruyuoxwq/37-homogenize-color-codes-to-one-value-name-rgba-hex-or-shorthand-hex-and-add-css-variables](https://trello.com/c/Ruyuoxwq/37-homogenize-color-codes-to-one-value-name-rgba-hex-or-shorthand-hex-and-add-css-variables)

2021-12-29 00:09 UTC, ohmlnz commented on App.js
> +        <Navigator />
[https://trello.com/c/sGOiRWZz/36-explore-refactoring-file-structure](https://trello.com/c/sGOiRWZz/36-explore-refactoring-file-structure)

2021-12-29 00:52 UTC, ohmlnz approved these changes

2021-12-29 00:52 UTC, ohmlnz commented
🔥🔥🔥

2021-12-29 00:52 UTC, merged